name: flutter_theme_with_getx
version: 1.0.0+1
publish_to: none
description: Flutter App Change Theme With Getx.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  google_fonts: ^2.1.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
